import helion  # type: ignore[import-untyped]
import helion.language as hl  # type: ignore[import-untyped]

from .appearance import apply_view_dependent_rgb, num_sh_bases, sh_basis
from .benchmarking import aggregate_step_metrics, compare_render_summary, select_compare_views, summarize_render_output
from .camera import LearnableCameraBundle, LearnableSharedIntrinsics
from .density_control import (
    apply_density_control,
    build_density_debug_summary,
    compute_prune_keep_mask,
    DensityControlResult,
    DensityDebugEntry,
    DensityDebugSummary,
    DensityScoreTerms,
    gradient_score,
    NormalizedRenderStats,
    normalize_render_stats,
    scale_score,
    select_clone_indices,
    select_split_indices,
    should_run_density_control,
    should_run_density_control_for_stage,
)
from .density_logging import DensityEventCallback, append_density_event_jsonl, emit_density_event
from .field import CanonicalGaussianField, ScaleAwareResidualHead
from .fixed_capacity import (
    CapacityAppendResult,
    append_rows_in_place,
    available_capacity,
    compact_rows_in_place,
    resolve_capacity,
)
from .gsplat_renderer import (
    clear_renderer_caches,
    prepare_visibility,
    render_gaussians,
    render_projection_meta,
    render_stats,
    render_stats_prepared,
    render_values,
    render_visibility_meta,
)
from .helion_gsplat_renderer import (
    helion_rasterize_values_op,
    prepare_visibility_helion,
    render_gaussians_helion,
    render_projection_meta_helion,
    render_stats_helion,
    render_stats_prepared_helion,
    render_values_helion,
    render_visibility_meta_helion,
)
from .observation_model import (
    apply_observation_model,
    area_downsample_chw,
    area_downsample_hwc,
    observation_render_size,
    observe_rgb,
    render_observe_rgb,
)
from .pipeline import PoseFreeGaussianSR, fit_posefree_gaussian_scene, render_arbitrary_scale
from .posefree_config import (
    AppearanceConfig,
    CameraInit,
    DensityControlConfig,
    FieldConfig,
    ObservationConfig,
    PoseFreeGaussianConfig,
    RenderConfig,
    TrainConfig,
)
from .progress_logging import ProgressEventCallback, append_progress_event_jsonl, emit_progress_event
from .warp_gsplat_renderer import (
    DataContracts,
    KERNEL_MAPPING_TABLE,
    MERMAID_PORT_FLOWCHART,
    PreparedVisibility,
    RasterConfig,
    WarpGSplatRasterizeValues,
    estimate_buffer_bytes_for_example,
    estimate_intersections,
    estimate_tiles,
    prepare_visibility_warp,
    render_gaussians_warp,
    render_stats_prepared_warp,
    render_visibility_meta_warp,
    render_stats_warp,
    render_values_warp,
)
from .warp_runtime import _WARP_AVAILABLE, _WARP_IMPORT_ERROR, require_warp, wp

__all__ = [
    "CameraInit",
    "RenderConfig",
    "ObservationConfig",
    "AppearanceConfig",
    "DensityControlConfig",
    "FieldConfig",
    "TrainConfig",
    "PoseFreeGaussianConfig",
    "LearnableSharedIntrinsics",
    "LearnableCameraBundle",
    "ScaleAwareResidualHead",
    "CanonicalGaussianField",
    "PoseFreeGaussianSR",
    "fit_posefree_gaussian_scene",
    "render_arbitrary_scale",
    "clear_renderer_caches",
    "ProgressEventCallback",
    "append_progress_event_jsonl",
    "emit_progress_event",
    "area_downsample_chw",
    "area_downsample_hwc",
    "observation_render_size",
    "observe_rgb",
    "apply_observation_model",
    "render_observe_rgb",
    "num_sh_bases",
    "sh_basis",
    "apply_view_dependent_rgb",
    "aggregate_step_metrics",
    "apply_density_control",
    "build_density_debug_summary",
    "CapacityAppendResult",
    "compare_render_summary",
    "DensityEventCallback",
    "DensityControlResult",
    "DensityDebugEntry",
    "DensityDebugSummary",
    "DensityScoreTerms",
    "NormalizedRenderStats",
    "append_density_event_jsonl",
    "emit_density_event",
    "compute_prune_keep_mask",
    "compact_rows_in_place",
    "gradient_score",
    "normalize_render_stats",
    "append_rows_in_place",
    "available_capacity",
    "resolve_capacity",
    "select_compare_views",
    "scale_score",
    "select_split_indices",
    "select_clone_indices",
    "should_run_density_control",
    "should_run_density_control_for_stage",
    "DataContracts",
    "PreparedVisibility",
    "RasterConfig",
    "prepare_visibility",
    "render_projection_meta",
    "render_visibility_meta",
    "render_stats_prepared",
    "render_values",
    "render_stats",
    "render_gaussians",
    "estimate_intersections",
    "estimate_tiles",
    "estimate_buffer_bytes_for_example",
    "KERNEL_MAPPING_TABLE",
    "MERMAID_PORT_FLOWCHART",
    "prepare_visibility_warp",
    "render_stats_prepared_warp",
    "render_visibility_meta_warp",
    "WarpGSplatRasterizeValues",
    "render_values_warp",
    "render_stats_warp",
    "render_gaussians_warp",
    "helion_rasterize_values_op",
    "prepare_visibility_helion",
    "render_projection_meta_helion",
    "render_visibility_meta_helion",
    "render_stats_prepared_helion",
    "render_values_helion",
    "render_stats_helion",
    "render_gaussians_helion",
    "summarize_render_output",
    "helion",
    "hl",
    "wp",
    "require_warp",
    "_WARP_AVAILABLE",
    "_WARP_IMPORT_ERROR",
]
